### ISSUE TITLE
Level 4 Question is false for all Answers

### ISSUE THREAD

**Issue by jcgardiner** [jenniferedwardsuk/BigAlPortPublic#1]
One of the questions the female allosaurus asks during the mate challenge is something to the effect of "Why is Big Al called big?"
Based on playing the game in the 2000s and on the actual history of Big Al, the right answer should be "Because his skeleton was so complete." But the game treats it like the wrong answer and she attacks you.

I have tested out the other possible answers and get the same outcome.

Whenever I encounter this question in the game, all I can do is move on without completing the mate challenge.

**Comment by jenniferedwardsuk** [comment]
Good catch! This is because the text for the first answer wraps onto two lines instead of one, but the clickable area for each answer stays one line high. So when you click on the answer 2 text, the third line clickable is activated and the game thinks you chose answer 3. If you click on the second line of answer 1, the game thinks you chose answer 2 and treats it as a correct answer.

Thanks for letting me know about this, I'll make a new build to correct it.

**Comment by jcgardiner** [comment]
I played the game again and can confirm the fix worked! Thank you.

I checked the repos and only saw commits from 8 months ago. Are there any commits where the code changes that fixed this can be viewed? Just curious ;)

**Comment by jenniferedwardsuk** [comment]
Thanks for checking the fix!

I didn't copy the change over to this repo because it was a small data change rather than a code change; I just made the mating answer shorter so that it wouldn't be wrapped onto two lines. Previously it was "Because he was the biggest Allosaurus ever found" - now it's "He was the biggest Allosaurus ever found".

Since this was the only mating question with a long enough answer to cause a problem, changing the data was safer than changing the code to support wrapping. :)

**Comment by jcgardiner** [comment]
Thanks! Good job on the game!
